### PR TITLE
Implemented test for API request and set up e2e workflow 

### LINKED ISSUE #26: Test API link with an integration test
The test should only check that the request goes out, not if there is a response.
The code snippet sending the request:
https://github.com/neurobagel/query-tool/blob/156902e5105db12f31032f314d05429f92abb004/components/QueryForm.vue#L178-L184

### LINKED ISSUE #53: Set up end to end test workflow
Set up a workflow to run end to end tests on PRs and dispatch.

### PR DESCRIPTION
**Pull request by rmanaem**
Closes #26 
Closes #53

### CODE REVIEW

**Review by jarmoza — CHANGES_REQUESTED** [review]
@rmanaem 🥣 

Rerun `APIRequest.cy.js`. I'm currently receiving this 404 error.

Screen Shot 2023-02-21 at 4 26 40 PM

**Comment by rmanaem** [comment]
@jarmoza Did you set the `API_QUERY_URL` env var?

**Comment by jarmoza** [comment]
@rmanaem I hadn't, but now I have and am getting the same error.

**Review by jarmoza — APPROVED** [review]
After a quick huddle, it was found that there is an extra `query/?` in the suggested environment variable `API_QUERY_URL` in the query tool's installation instructions.

👨‍🍳

**Comment by surchs** [comment]
> After a quick huddle, it was found that there is an extra `query/?` in the suggested environment variable `API_QUERY_URL` in the query tool's installation instructions.
> 
> man_cook

Cool. Is this something we should clarify in the docs / README?

**Comment by jarmoza** [comment]
@surchs Yes, @rmanaem mentioned that he would be updating the README.

**Pull request merged**
