### PR TITLE
Updated README.md

### LINKED ISSUE #56: Update README.md
- [x] Update the badge for component-test workflow
- [x] Replace the `npm` badge with a badge for e2e-test workflow

### PR DESCRIPTION
**Pull request by rmanaem**
Closes #56

### CODE REVIEW

**Review by jarmoza — APPROVED** [review]
All links functioning. 👨‍🍳

**Comment by surchs** [comment]
I see 
image
 when I look at the pre-rendered version of the README. Is that expected?

**Comment by rmanaem** [comment]
@surchs Which branch are u on?

**Comment by surchs** [comment]
@rmanaem I am looking at this PR: https://github.com/neurobagel/query-tool/pull/57/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by rmanaem** [comment]
@surchs I reckon it's a GitHub bug/issue cause the README.md renders just fine in the main branch

**Pull request merged**
