### PR TITLE
Adding Parkinson as diagnosis

### PR DESCRIPTION
**Pull request by surchs**
No tracking issue, just added Parkinson's diagnosis (because we have those data).

- also alphabetized the diagnosis keys

### CODE REVIEW

**Review by rmanaem — APPROVED** [review]
👨🏼‍🍳

**Comment by surchs** [comment]
Thanks @rmanaem , I'll wait with meeting this until we have discussed the performance issues. Seems like our Parkinson subjects are linked to slow queries

**Comment by surchs** [comment]
I'm going to close this PR for now. I think we will have to address this as part of the openneuro graph deployment

**Comment by rmanaem** [comment]
@surchs Do we need to keep the branch?

**Pull request closed without merging**
