### PR TITLE
[MAINT] Updated dropdown options and output files

### LINKED ISSUE #120: Update tool to reflect changes made to API
Once the OpenNeuro data is updated (https://github.com/neurobagel/project/issues/143) and the API is updated to adhere to the new model and data (https://github.com/neurobagel/api/issues/129):

- [x] update corresponding [examples of the outputs in our internal wiki](https://github.com/neurobagel/documentation/wiki/Query-Tool)
- [x] update dropdown options
- [x] replace `DatasetFilePath` with `DatasetID` in output files
- [x] update the `generateTSVString` method
- [x] update README.md
- [x] if possible, add some note (either directly in the column name or elsewhere) that the dataset uuid is just for merging the results TSVs and is not a persistent identifier (they're regenerated when the graph is remade)

### PR DESCRIPTION
**Pull request by rmanaem**
Closes #120
See also https://github.com/neurobagel/project/issues/141

Changes proposed in this pull request:

- Updated dropdown options for categorical fields
- Replaced `DatasetFilePath` with `DatasetID` in output files
- Updated README.md

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[BUG]`, `[DOC]`, `[INFRA]`, `[MAINT]`)
- [x] PR links to Github issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Code is properly formatted

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Review by jarmoza — CHANGES_REQUESTED** [review]
There is a current issue where the query tool reports X subjects available for an assessment tool but the output – at either level of detail – has zero rows.

**Comment by rmanaem** [comment]
@jarmoza Could you let me know which assessment tool option resulted in that behavior?

**Comment by jarmoza** [comment]
> @jarmoza Could you let me know which assessment tool option resulted in that behavior?

@rmanaem From what I'm seeing it's any one assessment tool except 'All'

**Review by jarmoza — APPROVED** [review]
🧑‍🍳 

@rmanaem, I noted the issue we found with the checkboxes and blank output results here: https://github.com/neurobagel/query-tool/issues/124

**Pull request merged**
